### PR TITLE
Update to ubuntu 20.04

### PR DESCRIPTION
**Pull request by fred-vogt**
What does this do ?
* updates the "build" container environment to ubuntu 20.04
* updates the `READM.md` to be clear about building from the 20.04 container
* adds the `iam` binary to the `.deb` package

## Links
* [aws/aws-sdk-cpp/CI/docker-file/Ubuntu/Dockerfile](https://github.com/aws/aws-sdk-cpp/blob/master/CI/docker-file/Ubuntu/Dockerfile)

### CODE REVIEW

**Comment by gfleury** [comment]
Maybe also change the .travis-ci to use Ubuntu 20, right now is pointing to xenial (which I guess is 16). What do you think?

**Comment by fred-vogt** [comment]
@gfleury - good point George.  After thinking about this overnight I think its best to build 2 .deb packages.

* curl3 / openssl 1.0 for ubuntu 16.04 / debian (stretch ?)
* curl4 / openssl 1.1 for ubuntu 18.04+ / debian (buster ?)

I'll do some more investigation.

**Comment by gfleury** [comment]
Souds like a good idea. Then we could do the first release with these .debs?

**Comment by gfleury** [comment]
@fred-vogt Should I merge or you can merge?

**Comment by fred-vogt** [comment]
I'll create a updated PR pretty soon.

**Comment by fred-vogt** [comment]
Quick update George,

I've been busy lately but will get to this pretty soon.

This is one of the highest priority items on my todo list.

Take care my friend.

**Comment by gfleury** [comment]
I was just thinking about you right now hahaha funny fact. I was actually
stalking your GitHub profile. :) No worries, I've been quite busy as well,
new work is always stressful.
Stay safe as well!

**Pull request closed without merging**
